# -*- coding: utf-8 -*-
"""Cellula_task1Bonus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAiBrecjVwJyYaNXqv9VzK06UP6gHSHk
"""

!pip install -U transformers datasets peft

import pandas as pd
import numpy as np

df = pd.read_csv("/content/cellula toxic data (1).csv")
df.drop_duplicates().shape

#converting each Toxic Category into a number
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["label"] = le.fit_transform(df["Toxic Category"])
label_map = {label: idx for idx, label in enumerate(le.classes_)}
label_map

#Splitting the dataset into 80% training data and 20% test data
from sklearn.model_selection import train_test_split
df["text"] = df["query"] + " " + df["image descriptions"]
x_train, x_test, y_train, y_test = train_test_split(
    df["text"] ,
    df["label"],
    test_size=0.2,
    random_state=42,
    stratify=df["label"] #splitting the data while preserving the class distribution instead of splitting randomly (for F1 score)
)

#converting pandas dataframes into dataset for the transformer model
from datasets import Dataset

train_dataset = Dataset.from_dict({
    "text": x_train.tolist(), #Dataset expects pure python lists
    "label": y_train.tolist()
})

test_dataset = Dataset.from_dict({
    "text": x_test.tolist(),
    "label": y_test.tolist()
})

from transformers import AutoTokenizer

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name) #loading the same tokenizer it was trained with

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)
#transformers use PyTorch tensors (converting the lists to tensors)
train_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)

test_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)

# sample = train_dataset[0]
# sample

#Adding a classification Head for pretrained DistilBERT
from transformers import AutoModelForSequenceClassification

num_labels = len(label_map)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels
)

#LoRA (freezes BERT, trains small adapters)
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=8, #rank(size of LoRA adapter)
    lora_alpha=16, #how strongly the LoRA update affects the model
    target_modules=["q_lin", "v_lin"],  # DistilBERT attention(attach adapters inside self-attention)
    lora_dropout=0.1, #applies only on LoRA adapters
    bias="none", #only train LoRA weights(do not train bias terms)
    task_type="SEQ_CLS" #(Sequence Classification task)
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

import numpy as np
from sklearn.metrics import f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred #tuple provided by the trainer
    predictions = np.argmax(logits, axis=1) #to find the index of the largest logit for each sample
    return {
        "macro_f1": f1_score(labels, predictions, average="macro")
    }

from transformers import TrainingArguments
from transformers import Trainer
training_args = TrainingArguments(
    output_dir="./bonus_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=15,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    report_to="none"
)

#Training
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

results = trainer.evaluate()
print(results)